version: '3'
services:
  web:
    build: ./web
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./web:/web
    depends_on:
      - "kafka"
  zookeeper:
    build: ./zookeeper
    ports:
      - 2181:2181
  kafka:
    build: ./kafka
    ports:
      - "9092:9092"
    depends_on:
      - "zookeeper"
